### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by JBYoshi** [AEnterprise/ChunkLoaderZ#4]
When running this mod with SpongeForge, it causes Minecraft to crash, because ChunkLoaderZ is using an `IProperty` that doesn't extend `PropertyHelper`.

[This line](https://github.com/AEnterprise/ChunkLoaderZ/blob/master/src/main/java/info/aenterprise/chunkloaderz/blocks/BlockAnhoredPearl.java#L34) in `BlockAnchoredPearl`:

``` java
private static final PropertyRange SCALE = new PropertyRange("scale", 0, 10, 1);
```

Should be replaced with Minecraft's `PropertyInt`, as the `interval` is 1 (the equivalent value in `PropertyInt`).

**Comment by AEnterprise** [comment]
the idea behind it was to make a more general usable property for me that i could re-use in other cases in another mod i'm working on but i'll replace it here if it causes issues

**Comment by AEnterprise** [comment]
uploaded a new version: http://minecraft.curseforge.com/projects/chunkloaderz/files/2275734

**Comment by JBYoshi** [comment]
Thanks!
